### GET access token with normal user credentials

POST http://localhost:8180/realms/water/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded


client_id=waterproject&client_secret=xayjgdlCfhVvskJffQheX8fSjqXS1qPB&username=said&password=said&grant_type=password&scope=openid

//saving the access token
> {% client.global.set("access_token", response.body.access_token) %}

### Access unsecured endpoint
GET http://localhost:8082/unsecured HTTP/1.1
Content_type: application/json

### Access secured endpoint
GET http://localhost:8082/secured HTTP/1.1
Content_type: application/json
Authorization: Bearer {{access_token}}

### Access secured endpoint via SecurityContextHolder
GET http://localhost:8082/secured/principal HTTP/1.1
Content_type: application/json
Authorization: Bearer {{access_token}}



### Access secured endpoint via annotation
GET localhost:8082/secured/annotation HTTP/1.1
Content_type: application/json
Authorization: Bearer {{access_token}}

### Access ships endpoint
GET http://localhost:8082/api/ships HTTP/1.1
Content_type: application/json
Authorization: Bearer {{access_token}}